# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70f7c94b0cef34ea7b96f4f84e369e519c7fa07b7f668a4d0c0f2b1b398a9dd37e1b94d98b3f6d0aff1af7fb73c8adb411900f81406d3fb62b82d2ad5019fb23

test:
  secret_key_base: 9b12bf540650df3a92f2ddd60f404b4ab1e232b305e8c5372890e463c6fce2089f42ea47b6921bfef2d5ac6130bcd794b3c4ef4ec375b8f7aee5fea757ed0119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
